version: '3.1'
services:
  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    image: stats-server-image
    volumes:
      - /var/log/explore/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
#
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build:
      context: ./main-service/ewm-service
      dockerfile: Dockerfile
    image: ewm-service-image
    volumes:
      - /var/log/explore/main
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      -   ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root
      - stats-service.url=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

